<?php
/**
 * @author 18th DigiTech Team
 * @copyright Copyright (c) 2020 18th DigiTech (https://www.18thdigitech.com)
 * @package Eighteentech_Givex
 */
?>
<div class="cms-page-view">
    <div class="content full">        
        <div class="breadcrumbs">
            <ul class="items">
                <li class="item home"><a href="<?= /* @noEscape */ $block->getBaseUrl(); ?>" title="Click here to return to the offyatree homepage">Home</a></li>
                <li class="item"><a href="<?= /* @noEscape */ $block->getBaseUrl(); ?>our-story/" title="Click here to return to page: About offyatree">About offyatree</a></li>
                <li class="item"><strong>offyatree Gift Cards</strong></li>
            </ul>
        </div>
        <h1 class="title"><?= /* @noEscape */ $block->escapeHtml(__('Check your Gift Card balance')) ?></h1>
    </div>
    <div class="gift-card">
        <form class="balance validate" method="post" id="balance-form" action="<?= /* @noEscape */ $block->getBaseUrl(); ?>givex/checkbalance/" onSubmit="return validateRecaptcha()">
            <section>
                <div class="field u-text-center">
                    <label for="gc-balance-number"><?= /* @noEscape */ $block->escapeHtml(__('Enter your Gift Card number')) ?></label>
                    <input id="gc-balance-number" class="gc-balance-number" name="giftcard_number" type="text" value="<?= htmlentities($block->getGiftcardNumber()); ?>" autocomplete="off" data-validate="{required:true}"/>
                    <?php $error = $block->getError(); ?>
                    <?php if (!empty($error)) : ?>
                        <label class="error" style="display:block;color: #e02b27;font-size:1.2rem;"><?= htmlentities($error); ?></label>
                    <?php endif; ?>
                </div>
                <div class="field" id="rcode">
                    <div class="captcha">
                        <div class="g-recaptcha" data-sitekey="<?= /* @noEscape */ $block->escapeHtml(__('$block->getSiteKey()')); ?>"
                             data-theme="light">
                         </div>
                    </div>
                    <div id="captcha-required" style="display:none;color: #e02b27;font-size:1.2rem;">
                        <?= /* @noEscape */ $block->escapeHtml(__('Please fill reCaptcha to continue.')) ?>
                    </div>
                </div>
            </section>

            <section class="submit">
                <button class="btn orange" type="submit"><?= /* @noEscape */ $block->escapeHtml(__('Submit')) ?></button>
            </section>

            <?php $balance = $block->getBalance(); ?>
            <?php if (!empty($balance)) : ?>
                <section class="balance-result">
                    <p>
                        <?= /* @noEscape */ $block->escapeHtml(__('Your balance is <strong class="price">$%1</strong>', $balance)); ?>
                    </p>
                    <?php if (!empty($block->getHasPreauth())) : ?>
                        <p>
                            <small><?= /* @noEscape */ $block->escapeHtml(__('Note: There is also an incomplete pre-authorisation on this gift card. If not confirmed, the balance will be restored after a few hours.')) ?>
                            </small>
                        </p>
                    <?php endif; ?>
                </section><!-- .balance-result -->
            <?php endif; ?>
        </form>
        <script type="text/x-magento-init">
            {
                "#balance-form": {
                    "validation": {}
                }
            }
        </script>
        <script type="text/javascript">
            function validateRecaptcha() {
                if (grecaptcha.getResponse() != "") {
                    document.getElementById("captcha-required").style.display = "none";
                    return true;
                } else {
                    document.getElementById("captcha-required").style.display = "block";
                    return false;
                }
            }
        </script>
        <script src="https://www.google.com/recaptcha/api.js" type="text/javascript" xml="space"></script>
    </div>
</div>